// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialScript_roles_rights : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialScript_roles_rights));
        
        string IMigrationMetadata.Id
        {
            get { return "201701301408443_initialScript_roles_rights"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
